name = "golf-proxy"
main = "golf_proxy_worker.js"
compatibility_date = "2026-09-19"
account_id = "bb148aa0b9c81b62e22cd305050d8810"

[[kv_namespaces]]
binding = "GOLF_SYNC"
id = "8698ae17677f4f08baa9ef1a1ed9a589"
